# Generated by Django 5.2.17 on 2026-09-06 14:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiBudget",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "allowance_nok",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "accounted_nok",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "nok_per_usd",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("12"), max_digits=7
                    ),
                ),
                (
                    "tax_reserve",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.25"), max_digits=5
                    ),
                ),
                ("approval_note", models.TextField(blank=True)),
                ("price_checked_on", models.DateField(default="2026-09-06")),
                ("price_valid_until", models.DateField(default="2026-11-21")),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("section", models.CharField(blank=True, max_length=120)),
                ("first_page", models.PositiveIntegerField(default=1)),
                ("last_page", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="LoginThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "window_started",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "kind",
                    models.CharField(
                        choices=[("guideline", "Guideline"), ("notes", "Study notes")],
                        default="guideline",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, max_length=160)),
                ("url", models.URLField(blank=True)),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("original_name", models.CharField(max_length=300)),
                ("file", models.FileField(upload_to="%Y/%m")),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("extraction_warning", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("published", models.PositiveIntegerField(default=0)),
                ("quarantined", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="study.chapter"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model", models.CharField(max_length=80)),
                ("purpose", models.CharField(max_length=30)),
                ("state", models.CharField(default="reserved", max_length=16)),
                ("reserved_nok", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "actual_nok",
                    models.DecimalField(decimal_places=4, max_digits=10, null=True),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("provider_response_id", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="study.generationjob",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stem", models.TextField()),
                (
                    "choices",
                    models.JSONField(
                        help_text="Exactly five objects with text and explanation."
                    ),
                ),
                (
                    "answer",
                    models.PositiveSmallIntegerField(
                        help_text="Correct option index, 0 to 4."
                    ),
                ),
                ("explanation", models.TextField()),
                ("learning_point", models.TextField()),
                (
                    "references",
                    models.JSONField(
                        default=list,
                        help_text="Page ID, section and supporting quote for each reference.",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("applied", "Applied"),
                            ("advanced", "Advanced"),
                        ],
                        default="applied",
                        max_length=12,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("case", "Clinical case"),
                            ("direct", "Direct knowledge"),
                            ("interpretation", "Interpretation"),
                        ],
                        default="case",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("quarantined", "Quarantined"),
                            ("retired", "Retired"),
                        ],
                        default="quarantined",
                        max_length=16,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("generated_by", models.CharField(blank=True, max_length=80)),
                ("verification", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="study.chapter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="study.source",
            ),
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("practice", "Practice"), ("exam", "Exam")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("break", "Break"),
                            ("complete", "Complete"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("part", models.PositiveSmallIntegerField(default=1)),
                (
                    "part_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("break_until", models.DateTimeField(blank=True, null=True)),
                ("cursor", models.PositiveIntegerField(default=1)),
                ("coverage", models.JSONField(default=dict)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("part", models.PositiveSmallIntegerField(default=1)),
                ("snapshot", models.JSONField()),
                ("choice_order", models.JSONField()),
                ("selected", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sure", "Sure"),
                            ("unsure", "Unsure"),
                            ("guessed", "Guessed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("correct", models.BooleanField(blank=True, null=True)),
                ("is_repeat", models.BooleanField(default=False)),
                ("review_flag", models.BooleanField(default=False)),
                ("progress_recorded", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="study.question"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="study.studysession",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topics",
                        to="study.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain__order", "title"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="study.topic",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chapters",
                to="study.topic",
            ),
        ),
        migrations.CreateModel(
            name="QuestionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen", models.PositiveIntegerField(default=0)),
                ("right", models.PositiveIntegerField(default=0)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("last_correct", models.BooleanField(blank=True, null=True)),
                ("last_confidence", models.CharField(blank=True, max_length=12)),
                ("last_answered", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("flagged", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "due_at"], name="study_quest_user_id_a8ffc7_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question"),
                        name="unique_user_question_progress",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourcePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="study.source",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "number"), name="unique_source_page"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studysession",
            index=models.Index(
                fields=["user", "status"], name="study_study_user_id_1a259c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionitem",
            constraint=models.UniqueConstraint(
                fields=("session", "position"), name="unique_session_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionitem",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="unique_session_question"
            ),
        ),
    ]
