# Generated by Django 5.2.17 on 2026-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="supporting_guidelines",
            field=models.ManyToManyField(
                blank=True, related_name="study_notes", to="study.source"
            ),
        ),
    ]
