# Generated by Django 5.2.17 on 2026-09-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_source_supporting_guidelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="notes_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="note_generation_jobs",
                to="study.source",
            ),
        ),
    ]
