# Generated by Django 5.2.17 on 2026-09-06 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0003_generationjob_notes_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("questions", "Questions"),
                    ("map", "Map learning objectives"),
                ],
                default="questions",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("coverage", "Increase coverage"),
                    ("variants", "Add useful variants"),
                ],
                default="coverage",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="testing_angle",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="LearningObjective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                (
                    "variant_limit",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("depth_reason", models.TextField(blank=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("blocked_reason", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="study.topic"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions",
                to="study.learningobjective",
            ),
        ),
        migrations.CreateModel(
            name="ObjectiveEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("references", models.JSONField(default=list)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objective_evidence",
                        to="study.chapter",
                    ),
                ),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="study.learningobjective",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.PositiveIntegerField()),
                ("end", models.PositiveIntegerField()),
                ("digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Not mapped"),
                            ("mapped", "Mapped"),
                            ("blocked", "Needs review"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("audit", models.JSONField(default=dict)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage_segments",
                        to="study.sourcepage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "start", "digest"),
                        name="unique_coverage_segment",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="learningobjective",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("variant_limit__gte", 1), ("variant_limit__lte", 3)
                ),
                name="objective_max_three",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectiveevidence",
            constraint=models.UniqueConstraint(
                fields=("objective", "chapter"), name="objective_chapter_evidence"
            ),
        ),
    ]
