# Generated by Django 5.2.17 on 2026-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_generationjob_kind_generationjob_strategy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="generator_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="reviewer_model",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
