# Generated by Django 5.2.17 on 2026-09-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_generationjob_generator_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="duplicate_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="source",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="format_copies",
                to="study.source",
            ),
        ),
    ]
