# Generated by Django 5.2.17 on 2026-09-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_source_duplicate_note_source_duplicate_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicall",
            name="cache_write_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apicall",
            name="cached_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apicall",
            name="reasoning_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apicall",
            name="service_tier",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="audit",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="retry_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="spend_limit_nok",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aliases",
                to="study.learningobjective",
            ),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="reconciliation_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="learningobjective",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Awaiting matching"),
                    ("complete", "Matched"),
                    ("blocked", "Needs review"),
                ],
                default="complete",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="objective_link_audit",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="kind",
            field=models.CharField(
                choices=[
                    ("questions", "Questions"),
                    ("map", "Map learning objectives"),
                    ("reconcile", "Match learning objectives"),
                    ("link_questions", "Link existing questions"),
                ],
                default="questions",
                max_length=16,
            ),
        ),
    ]
