# Generated by Django 5.2.17 on 2026-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_apicall_cache_write_tokens_apicall_cached_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="notes_first_location",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generationjob",
            name="notes_last_location",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
