# Generated by Django 5.2.17 on 2026-09-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0008_generationjob_notes_first_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_sha256", models.CharField(max_length=64)),
                ("layout_sha256", models.CharField(max_length=64)),
                ("text_sha256", models.CharField(max_length=64)),
                ("extractor", models.CharField(max_length=80)),
                ("text", models.TextField()),
                ("passages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading",
                        to="study.sourcepage",
                    ),
                ),
            ],
        ),
    ]
