# Generated by Django 5.2.17 on 2026-09-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0009_pagereading"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningobjective",
            name="inventory_key",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="coveragesegment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Not mapped"),
                    ("mapped", "Mapped"),
                    ("partial", "Partially mapped"),
                    ("blocked", "Unresolved"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
